In [1]:
import numpy as np
import pandas as pd
import xarray as xr
%matplotlib inline

In [2]:
xr.DataArray(np.random.randn(2,3))

<xarray.DataArray (dim_0: 2, dim_1: 3)>
array([[-0.41642861, -0.33708466,  0.40957323],
       [ 0.72625947,  0.26320945, -0.03576332]])
Coordinates:
  * dim_0    (dim_0) int64 0 1
  * dim_1    (dim_1) int64 0 1 2

In [11]:
data = xr.DataArray(np.random.randn(2,3), [('x', ['a', 'b']), ('y', [-2, 0, 2])])

In [12]:
print data

<xarray.DataArray (x: 2, y: 3)>
array([[-1.81672985,  0.79594557,  1.06009156],
       [ 0.65119728, -1.05987158,  0.51464388]])
Coordinates:
  * x        (x) |S1 'a' 'b'
  * y        (y) int64 -2 0 2


In [13]:
xr.DataArray(pd.Series(range(3), index=list('abc'), name='foo'))

<xarray.DataArray 'foo' (dim_0: 3)>
array([0, 1, 2])
Coordinates:
  * dim_0    (dim_0) object 'a' 'b' 'c'

In [14]:
data.values

array([[-1.81672985,  0.79594557,  1.06009156],
       [ 0.65119728, -1.05987158,  0.51464388]])

In [15]:
data.dims

('x', 'y')

In [16]:
data.coords

Coordinates:
  * x        (x) |S1 'a' 'b'
  * y        (y) int64 -2 0 2

In [17]:
data.attrs

OrderedDict()

In [20]:
data[[1]]

<xarray.DataArray (x: 1, y: 3)>
array([[ 0.65119728, -1.05987158,  0.51464388]])
Coordinates:
  * x        (x) |S1 'b'
  * y        (y) int64 -2 0 2

In [22]:
data.loc['b']

<xarray.DataArray (y: 3)>
array([ 0.65119728, -1.05987158,  0.51464388])
Coordinates:
    x        |S1 'b'
  * y        (y) int64 -2 0 2

In [31]:
data.isel(y=slice(-1))

<xarray.DataArray (x: 2, y: 2)>
array([[-1.81672985,  0.79594557],
       [ 0.65119728, -1.05987158]])
Coordinates:
  * x        (x) |S1 'a' 'b'
  * y        (y) int64 -2 0

In [32]:
data.mean(dim='y')

<xarray.DataArray (x: 2)>
array([ 0.01310243,  0.03532319])
Coordinates:
  * x        (x) |S1 'a' 'b'

In [33]:
a = xr.DataArray(np.random.randn(3), [data.coords['y']])

b = xr.DataArray(np.random.randn(4), dims='z')

In [35]:
a, b

(<xarray.DataArray (y: 3)>
 array([ 0.77462532,  0.23748713, -1.58299842])
 Coordinates:
   * y        (y) int64 -2 0 2, <xarray.DataArray (z: 4)>
 array([-0.59335201, -1.14071829,  0.10781373,  1.07008236])
 Coordinates:
   * z        (z) int64 0 1 2 3)

In [36]:
a + b

<xarray.DataArray (y: 3, z: 4)>
array([[ 0.18127331, -0.36609297,  0.88243905,  1.84470768],
       [-0.35586489, -0.90323117,  0.34530086,  1.30756949],
       [-2.17635043, -2.72371671, -1.47518469, -0.51291606]])
Coordinates:
  * y        (y) int64 -2 0 2
  * z        (z) int64 0 1 2 3

In [37]:
b + a

<xarray.DataArray (z: 4, y: 3)>
array([[ 0.18127331, -0.35586489, -2.17635043],
       [-0.36609297, -0.90323117, -2.72371671],
       [ 0.88243905,  0.34530086, -1.47518469],
       [ 1.84470768,  1.30756949, -0.51291606]])
Coordinates:
  * z        (z) int64 0 1 2 3
  * y        (y) int64 -2 0 2

In [ ]:
b