In [21]:
# Load data set and target values
import sys
sys.path.append('/home/peng/git/Machine_learning_for_reliability_analysis/Preprocess')
sys.path.append('/home/peng/git/Machine_learning_for_reliability_analysis/DAlgorithms')

import Preprocessdata
import RFclass

from __future__ import print_function
from __future__ import division

import logging
from sklearn.datasets import make_classification
from sklearn.cross_validation import cross_val_score

from sklearn.ensemble import RandomForestClassifier as RFC


from bayes_opt import BayesianOptimization
from pandas.core.frame import DataFrame
import numpy as np
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


p= Preprocessdata.standardprocess()


save_path = '/home/peng/Documents/Project_C/Turbofan/Dataset/'
results_path = '/home/peng/git/Machine_learning_for_reliability_analysis/RA_Risk/results/'
#names = xrange(0,28)

df = pd.read_csv(save_path + 'train_FD001_3_p20_.txt', header=0)

#df = pd.read_csv(save_path + 'train_FD001_2_disc.txt', header=0)
#df = df.sample(n=10000)
rad_stat = 2
seed = 'rf'

# drop the first column
df_1 = df.drop(df.columns[[0]], axis=1)
df_kmm = df_1.drop(df.columns[[24]], axis=1)
#df = df.sample(n=100)
print (df_1)

#### scale the training dataset first and then apply the rules to test set 
train, trainlabel, test, testlabel = p.scaledivd(df_1, 1.0)
#print (test[0:10])
test = train
testlabel = trainlabel*2

            2       3      4       5       6        7        8      9     10  \
0     -0.0012  0.0002  100.0  518.67  643.81  1607.37  1426.15  14.62  21.61   
1      0.0017 -0.0005  100.0  518.67  642.23  1581.60  1401.86  14.62  21.61   
2     -0.0019 -0.0005  100.0  518.67  642.19  1582.64  1401.59  14.62  21.61   
3      0.0029  0.0001  100.0  518.67  642.23  1594.45  1406.13  14.62  21.61   
4     -0.0033  0.0001  100.0  518.67  643.73  1603.63  1433.65  14.62  21.61   
5     -0.0017  0.0002  100.0  518.67  642.78  1601.21  1421.70  14.62  21.61   
6      0.0037  0.0002  100.0  518.67  642.94  1592.81  1410.77  14.62  21.61   
7     -0.0040  0.0001  100.0  518.67  642.37  1598.31  1402.54  14.62  21.61   
8      0.0023 -0.0003  100.0  518.67  643.14  1590.61  1425.93  14.62  21.61   
9     -0.0012 -0.0002  100.0  518.67  642.51  1586.16  1398.13  14.62  21.61   
10     0.0024  0.0003  100.0  518.67  642.87  1593.87  1418.54  14.62  21.61   
11    -0.0049 -0.0002  100.0  518.67  64

In [22]:

train_kmm = df_kmm
#train_kmm = test

In [23]:
from sklearn.cluster import KMeans

n_num = 3

k_means = KMeans(init='k-means++', n_clusters=n_num, n_init=10)
X = train_kmm
k_means.fit(train_kmm)

k_means_labels = k_means.labels_
k_means_cluster_centers = k_means.cluster_centers_
k_means_labels_unique = np.unique(k_means_labels)



In [13]:
label_turn = (trainlabel-1)*(-1)

In [14]:
print (np.shape(k_means_labels))
testlabel = label_turn
print (np.shape(testlabel))


(8349,)
(8349,)


In [24]:
print (np.shape(train_kmm))
print (k_means_labels[0:10])
#print (df_label_2['label'][0:10])

from sklearn.metrics.classification import accuracy_score, confusion_matrix, classification_report

print (confusion_matrix(k_means_labels,testlabel))
print( classification_report(k_means_labels, testlabel))
print (accuracy_score(k_means_labels,testlabel))

(12571, 24)
[2 0 0 0 1 0 0 0 0 0]
[[4086 4169 2222]
 [   0    0  691]
 [   0   53 1350]]
             precision    recall  f1-score   support

          0       1.00      0.39      0.56     10477
          1       0.00      0.00      0.00       691
          2       0.32      0.96      0.48      1403

avg / total       0.87      0.43      0.52     12571

0.432423832631


In [25]:
from sklearn.metrics import adjusted_mutual_info_score as ari

print (ari(k_means_labels,testlabel))

0.177158290304
